### ISSUE TITLE
Cursor is hidden under () {} []

### ISSUE THREAD

**Issue by omar2205** [cseelus/vim-colors-lucid#2] opened 2021-11-26 11:01 UTC
![image](https://user-images.githubusercontent.com/1373867/143570763-7915852f-cc60-401c-a6fc-0fbadb016392.png)

Is there a way to fix this?

**Comment by omar2205** [comment] 2021-11-26 11:15
I fixed it with 
```vim
hi MatchParen ctermfg=12 ctermbg=10 guifg=#c2027a guibg=#2b7a60
```

but is there a good color that matches the color scheme?

**Comment by cseelus** [comment] 2021-11-26 12:59
I assume your cursor is on the opening bracket, after 'uppercase'?

It should look something like this:
<img width="427" alt="Screen Shot 2021-11-26 at 13 57 59" src="https://user-images.githubusercontent.com/3188392/143584720-5507033a-f717-4e4f-a2e5-ead2aac4c4b2.png">

Which version of Vim are you using?

**Comment by omar2205** [comment] 2021-11-26 13:21
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 27 2021 18:57:19)

**Comment by cseelus** [comment] 2021-11-26 16:03
Weird. Are you seeing matching parents with other color schemes (without setting it manually)?

**Comment by omar2205** [comment] 2021-11-26 16:25
Yes,
![image](https://user-images.githubusercontent.com/1373867/143609301-373c7a5c-e110-462a-8655-21f5261bb689.png)

**Comment by cseelus** [comment] 2021-11-27 15:57
I've installed the latest version of VIM and this color scheme with it, since I'm using NeoVim these days. 
First I thought you are using an old version of VIM, but apparently 8.2 from over two years ago is the current one.
 
<img width="539" alt="Screen Shot 2021-11-27 at 16 55 55" src="https://user-images.githubusercontent.com/3188392/143688239-5d83d355-41ff-442b-a650-21cbb0cb9def.png">

I can't reproduce your problem even with VIM unfortunately, matching parenthesis work as expected:

<img width="507" alt="Screen Shot 2021-11-27 at 16 52 25" src="https://user-images.githubusercontent.com/3188392/143688144-79173c65-fc6f-4d89-9574-2eb18148b360.png">

Closing this for now, since I have to assume this is some configuration error. Feel free to add to this thread if you have further questions though.

**Closed as completed by cseelus** 2021-11-27 15:57 UTC
